quotes = [
    "The heliosheath is not the only door into the system.",
    "You have fought everything else that entered this realm. Will you fight a planet?.",
    "The dust has commingled, the Nine is forever changed.",
    "There is a door in the woods. It is opening.",
    "Do not be afraid. The Nine wish to be kind to you.",
    "Do not fear me. That is not why I am here.",
    "Do not be alarmed. I know no reason to cause you harm.",
    "The Nine's eye is still watching.",
    "You will not find the Nine that way, but they will find you.",
    "If you are here, it means the Nine are not done with you yet.",
    "The Nine see your valour.",
    "Do not go looking for the Nine. They will come to you.",
    "They want to know about you. It is an honour.",
    "I am here for a reason. I just… cannot remember it.",
    "I bring a message from the Nine.",
    "I have a message for you from the Nine, but I forget it.",
    "I do mean to explain, but every time I try, I lose the thread.",
    "One day, you will understand, Warlock.",
    "I have explained it the best that I can.",
    "I am trying to give you answers, Warlock. Believe me.",
    "What happens when every cell is dead?.",
    "You made the adaptations necessary to further organic life.",
    "Your cells can be more than cells.",
    "It is my fate to help you. This I know.",
    "I think you have terrible need of my gifts.",
    "These are from the Nine.",
    "The Nine show you these.",
    "I bring gifts of the Nine. Gifts you sorely need.",
    "Perhaps this is why the Nine sent me here.",
    "I come bearing help.",
    "My will is not my own. Is yours?",
    "Yours is a lonely existence.",
    "Is it your will to return?",
    "To do what you say, is to speak in a language of pure meaning.",
    "You face the strongest enemies in the system, and you still live? Interesting.",
    "I returned to the Tower to find it empty.",
    "The Traveler's song echoes on.",
    "I may be here when you return.",
    "Whatever happened would have been the will of the Nine and therefore right, but...I am glad you have won.",
    "I hope to be here again.",
    "I cannot promise I will be here when you return… if you return.",
    "It was the Nine's—now it is yours.",
    "Fugue-55 is the best gun in the game"
]

bansheequotes = [
    "Are those bite marks? Nasty...",
    "Best Exo I ever served under... up and vanished one night. That's war.",
    "Careful out there.",
    "I've seen this gun before. It's a fine old piece.",
    "Exos don't dream, he said. But what's dreams... and what's memory? Ah, just fix the gun, Banshee.",
    "Okay, go.",
    "Could change the gas blocker here.",
    "Day's off to a good start.",
    "Don't leave it so long next time.",
    "Early riser, huh?",
    "Goodbye, so long.",
    "Good time to come.",
    "Guardian.",
    "Have we met? I know that gun.",
    "I don't know if it scares the enemy, but it sure scares the hell outta me.",
    "I'll remember you next time... maybe.",
    "Keep that thing oiled Guardian.",
    "Keep us safe.",
    "Lives at stake. Unacceptable. Someone will pay for this.",
    "Tch. What do they expect me to do with this?",
    "Let's get you back out there.",
    "Ah, Crux. If we had a few more of these in the old days.",
    "Hmm... Not a moment too soon.",
    "Morning, Guardian.",
    "Never too early.",
    "New day, new gun.",
    "New shipment's just come in.",
    "Nothing like a new gun in the morning.",
    "Of course I can. I've forgotten more about guns than she's ever known.",
    "Keep this one clean or it jams.",
    "Okay, I can help with this.",
    "See you around.",
    "Shoddy, as if I wouldn't notice. All my wipes, seen all the tricks.",
    "Smart. Beat the morning rush.",
    "Ugh, how many times has my system been wiped? Forty-one, forty-two, forty... three?",
    "Until next time.",
    "Watch where you point that thing.",
    "Watch yourself.",
    "What do you need?",
    "You take care of that gun, Guardian.",
    "You've come to the right place.",
    "Nothing salvageable. What a mess.",
    "Too much flash. Sitting duck.",
    "Heat shield's on the fritz.",
    "Should upgrade that coil. Never enough time.",
    "Leaks radiation like a sieve.",
    "Bolt still jams.",
    "That sight's gonna get someone killed.",
    "Chromed molly. Now that's old fashioned.",
    "Nope. No, no.",
    "Woke howling on the field where he fell. Never gets better for some.",
    "Omolon is late again... I don't have time for this.",
    "Told 'em it wouldn't stop Cabal... some men never listen.",
    "Do we have a problem here?",
    "I swear I've seen this before, these marks. Uh, eh, it all blends into one.",
    "Very good, must let Cassoid know this is adequate, but don't let it get to their heads.",
    "Late shipment again. Strikes, shortages, always some excuse.",
    "They say silence speaks volumes, but so do words.",
    "Hm, why not? That'll work.",
    "All these lives on the line, and Daito wants more glimmer. What goes through their heads down there?",
    "Reef work. Alright, not bad. Too fancy, we'll fix that.",
    "First time was incompetence, this is sabotage. I'll get to the bottom of this.",
    "The fire was below us as we dropped on the coast.",
    "Never seen one of those. Always something new.",
    "I know you, don't I?",
    "Say what you like about the Cabal, they know guns.",
    "What was her name, fierce eyes, full of light. The hell was it?",
    "Hey.",
    "What? What are you looking at me like that for? What do you remember?",
    "I can work with this.",
    "Now that's good.",
    "First time was incompetence. This is sabotage. Get to the bottom of this.",
    "You look familiar... are you killers?",
    "Silence, huh? I was the same when I came back from the front.",
    "Fugue-55 is the best gun in the game"
]
    
