quotes = [
    "The heliosheath is not the only door into the system.",
    "You have fought everything else that entered this realm. Will you fight a planet?.",
    "The dust has commingled, the Nine is forever changed.",
    "There is a door in the woods. It is opening.",
    "Do not be afraid. The Nine wish to be kind to you.",
    "Do not fear me. That is not why I am here.",
    "Do not be alarmed. I know no reason to cause you harm.",
    "The Nine's eye is still watching.",
    "You will not find the Nine that way, but they will find you.",
    "If you are here, it means the Nine are not done with you yet.",
    "The Nine see your valour.",
    "Do not go looking for the Nine. They will come to you.",
    "They want to know about you. It is an honour.",
    "I am here for a reason. I just… cannot remember it.",
    "I bring a message from the Nine.",
    "I have a message for you from the Nine, but I forget it.",
    "I do mean to explain, but every time I try, I lose the thread.",
    "One day, you will understand, Warlock.",
    "I have explained it the best that I can.",
    "I am trying to give you answers, Warlock. Believe me.",
    "What happens when every cell is dead?.",
    "You made the adaptations necessary to further organic life.",
    "Your cells can be more than cells.",
    "It is my fate to help you. This I know.",
    "I think you have terrible need of my gifts.",
    "These are from the Nine.",
    "The Nine show you these.",
    "I bring gifts of the Nine. Gifts you sorely need.",
    "Perhaps this is why the Nine sent me here.",
    "I come bearing help.",
    "My will is not my own. Is yours?",
    "Yours is a lonely existence.",
    "Is it your will to return?",
    "To do what you say, is to speak in a language of pure meaning.",
    "You face the strongest enemies in the system, and you still live? Interesting.",
    "I returned to the Tower to find it empty.",
    "The Traveler's song echoes on.",
    "I may be here when you return.",
    "Whatever happened would have been the will of the Nine and therefore right, but...I am glad you have won.",
    "I hope to be here again.",
    "I cannot promise I will be here when you return… if you return.",
    "It was the Nine's—now it is yours."
]
    
